/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Case */
        post: operations["upload_case_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/dismissals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dismissals */
        get: operations["dismissals_api_cases__case_id__dismissals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/entities/{etype}/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity */
        get: operations["entity_api_cases__case_id__entities__etype___eid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_cases__case_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Context */
        get: operations["event_context_api_cases__case_id__events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incidents */
        get: operations["incidents_api_cases__case_id__incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident Detail */
        get: operations["incident_detail_api_cases__case_id__incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/incidents/{incident_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay */
        get: operations["replay_api_cases__case_id__incidents__incident_id__replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/naive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Naive */
        get: operations["naive_api_cases__case_id__naive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_api_cases__case_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/report.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_cases__case_id__report_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal */
        post: operations["reveal_api_cases__case_id__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_cases__case_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/suspects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suspects */
        get: operations["suspects_api_cases__case_id__suspects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/heldout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Heldout
         * @description Held-out test: a template written after the engine was frozen (insider misuse, T3).
         */
        get: operations["eval_heldout_api_eval_heldout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eval Latest */
        get: operations["eval_latest_api_eval_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_api_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @enum {string}
         */
        Action: "login" | "logout" | "sudo" | "su" | "useradd" | "group_add" | "http" | "conn" | "file_read" | "file_write" | "proc_exec" | "cron_add" | "key_add" | "log_clear" | "other";
        /** ActorCluster */
        ActorCluster: {
            /** Id */
            id: string;
            /** Linkage Evidence */
            linkage_evidence: components["schemas"]["LinkageEvidence"][];
            /** Member Ips */
            member_ips: string[];
            /** Total Weight */
            total_weight: number;
        };
        /** AttackGraph */
        AttackGraph: {
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Frames */
            frames: components["schemas"]["ReplayFrame"][];
            /** Incident Id */
            incident_id: string;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
        };
        /** AttackStep */
        AttackStep: {
            /** Actor Entity */
            actor_entity?: string | null;
            /** Edge Justification */
            edge_justification?: components["schemas"]["PredicateInstance"][];
            /** Event Ids */
            event_ids: string[];
            /** Id */
            id: string;
            /**
             * Inferred
             * @default false
             */
            inferred: boolean;
            /** Order */
            order: number;
            /** Signal Ids */
            signal_ids: string[];
            stage: components["schemas"]["Stage"];
            /** Summary Count */
            summary_count?: number | null;
            /**
             * T End
             * Format: date-time
             */
            t_end: string;
            /**
             * T Start
             * Format: date-time
             */
            t_start: string;
            /** Target Entity */
            target_entity?: string | null;
        };
        /** Body_upload_case_api_cases_post */
        Body_upload_case_api_cases_post: {
            /** Files */
            files: string[];
        };
        /** CaseCreated */
        CaseCreated: {
            /** Case Id */
            case_id: string;
        };
        /**
         * CaseSource
         * @enum {string}
         */
        CaseSource: "upload" | "scenario";
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "created" | "parsing" | "analyzing" | "ready" | "failed";
        /** CaseSummary */
        CaseSummary: {
            /** Case Id */
            case_id: string;
            /**
             * Contract Version
             * @default 1.1.0
             */
            contract_version: string;
            /** Error */
            error?: string | null;
            funnel: components["schemas"]["Funnel"];
            /** Name */
            name: string;
            parse_report?: components["schemas"]["ParseReport"] | null;
            /** Pipeline Version */
            pipeline_version: string;
            scenario_params?: components["schemas"]["ScenarioParams"] | null;
            /** Scenario Seed */
            scenario_seed?: number | null;
            source: components["schemas"]["CaseSource"];
            status: components["schemas"]["CaseStatus"];
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "authentication" | "network" | "file" | "process" | "web" | "iam";
        /** Claim */
        Claim: {
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Facts */
            facts?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Incident Id */
            incident_id: string;
            /** Step Id */
            step_id?: string | null;
            /** Text */
            text: string;
            type: components["schemas"]["ClaimType"];
        };
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "ENTRY" | "ACTION" | "PIVOT" | "ESCALATION" | "STAGING" | "EXFIL" | "GAP" | "CAVEAT" | "DISMISSAL";
        /**
         * Criticality
         * @enum {string}
         */
        Criticality: "low" | "med" | "high";
        /** Dismissal */
        Dismissal: {
            /** Counter Evidence */
            counter_evidence?: components["schemas"]["EvidenceRef"][];
            /**
             * Decision
             * @default not_flagged
             */
            decision: string;
            /** Entity */
            entity: string;
            /** Id */
            id: string;
            /** Reasons */
            reasons: string[];
            /** Would Flag If */
            would_flag_if?: string | null;
        };
        /** DismissalList */
        DismissalList: {
            /** Case Id */
            case_id: string;
            /** Dismissals */
            dismissals: components["schemas"]["Dismissal"][];
        };
        /** Entity */
        Entity: {
            /** Attrs */
            attrs?: {
                [key: string]: unknown;
            };
            /** @default med */
            criticality: components["schemas"]["Criticality"];
            /** First Seen */
            first_seen?: string | null;
            /** Id */
            id: string;
            /** Internal */
            internal?: boolean | null;
            /** Last Seen */
            last_seen?: string | null;
            /** @default unknown */
            role: components["schemas"]["EntityRole"];
            /** Subnet */
            subnet?: string | null;
            type: components["schemas"]["EntityType"];
        };
        /** EntityProfile */
        EntityProfile: {
            /** Baseline */
            baseline?: {
                [key: string]: unknown;
            };
            entity: components["schemas"]["Entity"];
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            /** Observed */
            observed?: {
                [key: string]: unknown;
            };
        };
        /**
         * EntityRole
         * @enum {string}
         */
        EntityRole: "attacker_infra" | "compromised_account" | "pivot_host" | "victim_host" | "noisy_benign" | "unknown";
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "user" | "ip" | "host" | "actor_cluster";
        /** EvalReport */
        EvalReport: {
            /** By Template */
            by_template?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** By Tier */
            by_tier?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Metrics */
            metrics?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Misses */
            misses?: {
                [key: string]: unknown;
            }[];
            /** N Scenarios */
            n_scenarios: number;
            /** Pipeline Version */
            pipeline_version: string;
            /** Seeds */
            seeds?: number[];
        };
        /** Event */
        Event: {
            action: components["schemas"]["Action"];
            /** Attrs */
            attrs?: {
                [key: string]: unknown;
            };
            /** Bytes In */
            bytes_in?: number | null;
            /** Bytes Out */
            bytes_out?: number | null;
            /** Case Id */
            case_id: string;
            category: components["schemas"]["Category"];
            /** Dst Ip */
            dst_ip?: string | null;
            /** Dst Port */
            dst_port?: number | null;
            /** File Id */
            file_id: string;
            /** Host */
            host?: string | null;
            /** Id */
            id: string;
            /** Line No */
            line_no: number;
            /** Object */
            object?: string | null;
            /** @default unknown */
            outcome: components["schemas"]["Outcome"];
            /** Parse Flags */
            parse_flags?: string[];
            /** Raw Text */
            raw_text: string;
            /** Session Id */
            session_id?: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Src Ip */
            src_ip?: string | null;
            /** Ts Original */
            ts_original: string;
            /**
             * Ts Utc
             * Format: date-time
             */
            ts_utc: string;
            /**
             * Tz Assumed
             * @default false
             */
            tz_assumed: boolean;
            /** User */
            user?: string | null;
            /** User Agent */
            user_agent?: string | null;
        };
        /** EventContext */
        EventContext: {
            /** After */
            after: string[];
            /** Before */
            before: string[];
            event: components["schemas"]["Event"];
            /** File Name */
            file_name: string;
            /** Line No */
            line_no: number;
            /** Producing Signals */
            producing_signals?: string[];
        };
        /** EventsPage */
        EventsPage: {
            /** Case Id */
            case_id: string;
            /** Events */
            events: components["schemas"]["Event"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /** Event Id */
            event_id: string;
            /** Note */
            note?: string | null;
            /** @default supports */
            role: components["schemas"]["EvidenceRole"];
        };
        /**
         * EvidenceRole
         * @enum {string}
         */
        EvidenceRole: "supports" | "context" | "contradicts";
        /** Funnel */
        Funnel: {
            /**
             * Events
             * @default 0
             */
            events: number;
            /**
             * Incidents
             * @default 0
             */
            incidents: number;
            /**
             * Linked Signals
             * @default 0
             */
            linked_signals: number;
            /**
             * Signals
             * @default 0
             */
            signals: number;
            /**
             * Watchlist
             * @default 0
             */
            watchlist: number;
        };
        /** Gap */
        Gap: {
            /** Description */
            description: string;
            /** Host */
            host?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            missing_predicate?: components["schemas"]["PredicateInstance"] | null;
            /** T End */
            t_end?: string | null;
            /** T Start */
            t_start?: string | null;
        };
        /** GraphEdge */
        GraphEdge: {
            /**
             * Count
             * @default 1
             */
            count: number;
            /** Event Ids */
            event_ids?: string[];
            /** Id */
            id: string;
            /**
             * Inferred
             * @default false
             */
            inferred: boolean;
            /** Label */
            label: string;
            /** Predicate */
            predicate?: string | null;
            /** Source */
            source: string;
            /**
             * T End
             * Format: date-time
             */
            t_end: string;
            /**
             * T Start
             * Format: date-time
             */
            t_start: string;
            /** Target */
            target: string;
        };
        /** GraphNode */
        GraphNode: {
            /** @default med */
            criticality: components["schemas"]["Criticality"];
            /** First Seen */
            first_seen?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** @default unknown */
            role: components["schemas"]["EntityRole"];
            stage?: components["schemas"]["Stage"] | null;
            type: components["schemas"]["EntityType"];
        };
        /** GroundTruth */
        GroundTruth: {
            /** Attacker Ips */
            attacker_ips?: string[];
            /** Compromised Users */
            compromised_users?: string[];
            /** Decoys */
            decoys?: components["schemas"]["TruthDecoy"][];
            /** Entry Vector */
            entry_vector?: string | null;
            /** Exfil Dst Ips */
            exfil_dst_ips?: string[];
            /** Files */
            files?: {
                [key: string]: number;
            };
            /** Gaps */
            gaps?: components["schemas"]["TruthGap"][];
            /**
             * N Events Rendered
             * @default 0
             */
            n_events_rendered: number;
            params: components["schemas"]["ScenarioParams"];
            /** Pivot Hosts */
            pivot_hosts?: string[];
            /** Scenario Id */
            scenario_id: string;
            /** Seed */
            seed: number;
            /** Stages */
            stages?: components["schemas"]["TruthStage"][];
            /**
             * T End
             * Format: date-time
             */
            t_end: string;
            /**
             * T Start
             * Format: date-time
             */
            t_start: string;
            /** Template */
            template: string;
            /** Victim Hosts */
            victim_hosts?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Contract Version
             * @default 1.1.0
             */
            contract_version: string;
            /** Pipeline Version */
            pipeline_version: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** Hypothesis */
        Hypothesis: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @default entry
             */
            kind: string;
            /** Probability */
            probability: number;
            /** Signal Ids */
            signal_ids: string[];
        };
        /** Incident */
        Incident: {
            /** Confidence */
            confidence: number;
            /** Entities */
            entities: string[];
            /** Entry Hypotheses */
            entry_hypotheses?: components["schemas"]["Hypothesis"][];
            /** Gaps */
            gaps?: components["schemas"]["Gap"][];
            /** Id */
            id: string;
            /** Scenario Id */
            scenario_id?: string | null;
            /** Score */
            score: number;
            /** Signal Ids */
            signal_ids: string[];
            /** Stages Covered */
            stages_covered?: components["schemas"]["Stage"][];
            status: components["schemas"]["IncidentStatus"];
            /** Steps */
            steps?: components["schemas"]["AttackStep"][];
            /**
             * T End
             * Format: date-time
             */
            t_end: string;
            /**
             * T Start
             * Format: date-time
             */
            t_start: string;
            /** Title */
            title: string;
            watchlist_priority?: components["schemas"]["WatchlistPriority"] | null;
            /** Watchlist Reason */
            watchlist_reason?: string | null;
        };
        /** IncidentDetail */
        IncidentDetail: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Dismissals */
            dismissals?: components["schemas"]["Dismissal"][];
            incident: components["schemas"]["Incident"];
            /** Links */
            links?: components["schemas"]["Link"][];
            score_breakdown: components["schemas"]["ScoreBreakdown"];
            /** Signals */
            signals?: components["schemas"]["Signal"][];
        };
        /** IncidentList */
        IncidentList: {
            /** Case Id */
            case_id: string;
            /** Incidents */
            incidents: components["schemas"]["Incident"][];
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "incident" | "watchlist";
        /** Link */
        Link: {
            kind: components["schemas"]["LinkKind"];
            /** Reason */
            reason: string;
            /** Signal A */
            signal_a: string;
            /** Signal B */
            signal_b: string;
            via?: components["schemas"]["PredicateInstance"] | null;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /**
         * LinkKind
         * @enum {string}
         */
        LinkKind: "predicate" | "soft";
        /** LinkageEvidence */
        LinkageEvidence: {
            /** Detail */
            detail?: string | null;
            /** Kind */
            kind: string;
            /** Weight */
            weight: number;
        };
        /** MatchResult */
        MatchResult: {
            /** False Positives */
            false_positives: string[];
            /** Hits */
            hits: string[];
            /** Kind */
            kind: string;
            /** Misses */
            misses: string[];
            /** Predicted */
            predicted: string[];
            /** Truth */
            truth: string[];
        };
        /** NaiveAlert */
        NaiveAlert: {
            /** Detector */
            detector: string;
            /** Entity */
            entity: string;
            /** Severity */
            severity: number;
            /** Signal Id */
            signal_id: string;
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** Title */
            title: string;
        };
        /** NaiveView */
        NaiveView: {
            /** Alerts */
            alerts: components["schemas"]["NaiveAlert"][];
            /** Case Id */
            case_id: string;
        };
        /**
         * Outcome
         * @enum {string}
         */
        Outcome: "success" | "failure" | "unknown";
        /** ParseReport */
        ParseReport: {
            /** Events Total */
            events_total: number;
            /** Files */
            files: components["schemas"]["SourceFile"][];
            /** Hosts */
            hosts?: string[];
            /** Lines Quarantined */
            lines_quarantined: number;
            /** Lines Skipped */
            lines_skipped: number;
            /** Lines Total */
            lines_total: number;
            /** Notes */
            notes?: string[];
            /** T Max */
            t_max?: string | null;
            /** T Min */
            t_min?: string | null;
        };
        /** PredicateInstance */
        PredicateInstance: {
            /** Args */
            args?: {
                [key: string]: string;
            };
            name: components["schemas"]["PredicateName"];
            /** T */
            t?: string | null;
        };
        /**
         * PredicateName
         * @enum {string}
         */
        PredicateName: "credential_compromised" | "has_access" | "privileged" | "foothold" | "discovered" | "staged" | "exfiltrated" | "persisted";
        /** ReplayFrame */
        ReplayFrame: {
            active_stage?: components["schemas"]["Stage"] | null;
            /** Claim Id */
            claim_id?: string | null;
            /** Edges Added */
            edges_added?: string[];
            /** Nodes Added */
            nodes_added?: string[];
            /**
             * T
             * Format: date-time
             */
            t: string;
        };
        /** RevealResponse */
        RevealResponse: {
            /** Case Id */
            case_id: string;
            /** Matches */
            matches: components["schemas"]["MatchResult"][];
            scorecard: components["schemas"]["Scorecard"];
            truth: components["schemas"]["GroundTruth"];
        };
        /** RuleMeta */
        RuleMeta: {
            /** Falsepositives */
            falsepositives?: string[];
            /** Level */
            level: string;
            /** References */
            references?: string[];
            /** Tags */
            tags?: string[];
        };
        /**
         * ScenarioParams
         * @description Validated ranges = the only knobs the UI may expose (sliders are capped here).
         */
        ScenarioParams: {
            /**
             * Clock Skew S
             * @default 0
             */
            clock_skew_s: number;
            /**
             * Dup Rate
             * @default 0
             */
            dup_rate: number;
            /**
             * Ip Rotation
             * @default 1
             */
            ip_rotation: number;
            /**
             * Log Loss
             * @default 0
             */
            log_loss: number;
            /**
             * Malformed Rate
             * @default 0
             */
            malformed_rate: number;
            /**
             * Noise
             * @default 1
             */
            noise: number;
            /**
             * Scale
             * @default 1
             */
            scale: number;
            /**
             * Shuffle
             * @default 0
             */
            shuffle: number;
            /**
             * Stealth
             * @default 0.5
             */
            stealth: number;
            /**
             * Template
             * @default T1
             */
            template: string;
            /**
             * With Decoys
             * @default true
             */
            with_decoys: boolean;
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            params?: components["schemas"]["ScenarioParams"];
            /** Seed */
            seed: number;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Bonuses */
            bonuses?: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
            /** Confidence Parts */
            confidence_parts?: {
                [key: string]: number;
            };
            /** Final */
            final: number;
            /** Incident Id */
            incident_id: string;
            /** Items */
            items: components["schemas"]["ScoreItem"][];
        };
        /** ScoreItem */
        ScoreItem: {
            /** Consequence Factor */
            consequence_factor: number;
            /** Contribution */
            contribution: number;
            /** Signal Id */
            signal_id: string;
            /** Strength */
            strength: number;
        };
        /** Scorecard */
        Scorecard: {
            /** Alert Compression */
            alert_compression?: number | null;
            /** Attacker Ip Recall */
            attacker_ip_recall?: number | null;
            /** Baselines */
            baselines?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Cluster Purity */
            cluster_purity?: number | null;
            /** Compromised User Recall */
            compromised_user_recall?: number | null;
            /**
             * False Suspect Count
             * @default 0
             */
            false_suspect_count: number;
            /** Gap Recall */
            gap_recall?: number | null;
            /** Runtime Ms */
            runtime_ms?: number | null;
            /** Stage Order Accuracy */
            stage_order_accuracy?: number | null;
        };
        /** Signal */
        Signal: {
            /** Confidence */
            confidence: number;
            /**
             * Criticality Mult
             * @default 1
             */
            criticality_mult: number;
            /** Detector */
            detector: string;
            /** Entities */
            entities: string[];
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Explanation Params */
            explanation_params?: {
                [key: string]: unknown;
            };
            /** Explanation Template */
            explanation_template: string;
            /** Features */
            features?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Produces */
            produces?: components["schemas"]["PredicateInstance"][];
            /**
             * Rarity
             * @default 0.5
             */
            rarity: number;
            /** Requires */
            requires?: components["schemas"]["PredicateInstance"][];
            rule_meta: components["schemas"]["RuleMeta"];
            /** Severity */
            severity: number;
            stage_hint: components["schemas"]["Stage"];
            /**
             * T End
             * Format: date-time
             */
            t_end: string;
            /**
             * T Start
             * Format: date-time
             */
            t_start: string;
            /** Title */
            title: string;
        };
        /** SourceFile */
        SourceFile: {
            /** Case Id */
            case_id: string;
            /** Detected Format */
            detected_format: string;
            /** Flag Counts */
            flag_counts?: {
                [key: string]: number;
            };
            /** Host Hint */
            host_hint?: string | null;
            /** Id */
            id: string;
            /** Lines Parsed */
            lines_parsed: number;
            /** Lines Quarantined */
            lines_quarantined: number;
            /** Lines Skipped */
            lines_skipped: number;
            /** Lines Total */
            lines_total: number;
            /** Name */
            name: string;
            /** Parser Conf */
            parser_conf: number;
            /** Sha1 */
            sha1: string;
            /** Skipped Reasons */
            skipped_reasons?: {
                [key: string]: number;
            };
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "auth" | "web" | "net" | "audit" | "sys";
        /**
         * Stage
         * @description Fixed kill-chain taxonomy (ATT&CK tactic names). Order = STAGE_ORDER.
         * @enum {string}
         */
        Stage: "RECON" | "INITIAL_ACCESS" | "EXECUTION" | "PERSISTENCE" | "PRIV_ESC" | "DISCOVERY" | "LATERAL_MOVEMENT" | "COLLECTION" | "EXFILTRATION";
        /** Suspect */
        Suspect: {
            actor_cluster?: components["schemas"]["ActorCluster"] | null;
            /** Chain Score */
            chain_score: number;
            /**
             * Distinct Stages
             * @default 0
             */
            distinct_stages: number;
            entity: components["schemas"]["Entity"];
            /** Risk Ledger */
            risk_ledger?: [
                string,
                number
            ][];
            role: components["schemas"]["EntityRole"];
            /** Signal Ids */
            signal_ids?: string[];
        };
        /** SuspectList */
        SuspectList: {
            /** Case Id */
            case_id: string;
            /** Suspects */
            suspects: components["schemas"]["Suspect"][];
        };
        /** TruthDecoy */
        TruthDecoy: {
            /** Entity */
            entity: string;
            /** Kind */
            kind: string;
            /** Refs */
            refs?: components["schemas"]["TruthRef"][];
        };
        /** TruthGap */
        TruthGap: {
            /** Host */
            host: string;
            /** Kind */
            kind: string;
            /**
             * N Dropped
             * @default 0
             */
            n_dropped: number;
            /** Source */
            source: string;
            /**
             * T End
             * Format: date-time
             */
            t_end: string;
            /**
             * T Start
             * Format: date-time
             */
            t_start: string;
        };
        /** TruthRef */
        TruthRef: {
            /** File */
            file: string;
            /** Line */
            line: number;
        };
        /** TruthStage */
        TruthStage: {
            /** Actor User */
            actor_user?: string | null;
            /** Host */
            host?: string | null;
            /** Refs */
            refs?: components["schemas"]["TruthRef"][];
            stage: components["schemas"]["Stage"];
            /**
             * T End
             * Format: date-time
             */
            t_end: string;
            /**
             * T Start
             * Format: date-time
             */
            t_start: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WatchlistPriority
         * @enum {string}
         */
        WatchlistPriority: "normal" | "high";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_case_api_cases_post: {
        parameters: {
            query?: {
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_case_api_cases_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismissals_api_cases__case_id__dismissals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DismissalList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_api_cases__case_id__entities__etype___eid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                etype: string;
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_cases__case_id__events_get: {
        parameters: {
            query?: {
                q?: string | null;
                host?: string | null;
                user?: string | null;
                ip?: string | null;
                action?: string | null;
                outcome?: string | null;
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_context_api_cases__case_id__events__event_id__get: {
        parameters: {
            query?: {
                context?: number;
            };
            header?: never;
            path: {
                case_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incidents_api_cases__case_id__incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_detail_api_cases__case_id__incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_api_cases__case_id__incidents__incident_id__replay_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    naive_api_cases__case_id__naive_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NaiveView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_api_cases__case_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_cases__case_id__report_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_api_cases__case_id__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_cases__case_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspects_api_cases__case_id__suspects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuspectList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eval_heldout_api_eval_heldout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalReport"];
                };
            };
        };
    };
    eval_latest_api_eval_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalReport"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    create_scenario_api_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
